### PR TITLE
sapphireTestnetIntegration

### LINKED ISSUE #33: Sapphire Testnet Integration
DoD:
- [ ] Make the integration with the sapphire testnet and be sure that it works as expected

### PR DESCRIPTION
**Pull request by kdetry**
Fixes #33

### CODE REVIEW

**Comment by KatunaNorbert** [comment]
Screenshot 2023-08-29 at 11 07 45

Subscription is stuck in 'Loading...' for socket provided asset

**Comment by KatunaNorbert** [comment]
There was also an issue with the progress bar, but I fixed it inside pdr-web: https://github.com/oceanprotocol/pdr-web/pull/131

**Comment by kdetry** [comment]
https://github.com/oceanprotocol/pdr-web/pull/137

**Comment by kdetry** [comment]
> Screenshot 2023-08-29 at 11 07 45
> Subscription is stuck in 'Loading...' for socket provided asset

I solved here:
https://github.com/oceanprotocol/pdr-web/pull/137

**Review by KatunaNorbert — APPROVED** [review]

**Pull request merged**
